med_diag/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient_app.urls', namespace='patient_app')),
    path('echo/', include('med_test1_app.urls', namespace='med_test1_app')),
    path('us/', include('med_test2_app.urls', namespace='med_test2_app')),
    path('', include('user_app.urls', namespace='user_app')),
    # path('', include('authApp.urls')),
]

med_test1_app/urls.py
from django.urls import path

from . import views

app_name='med_test1_app'

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create_med_test1_report, name="create_med_test1_report"),
    path("read/", views.read_med_test1_report, name="read_med_test1_report"),
    path("update/", views.update_med_test1_report, name="update_med_test1_report"),
    path("delete/", views.delete_med_test1_report, name="delete_med_test1_report"),
    path('validate/', views.validate, name='validate'),
    path('test/', views.test, name='test'),

    path("print_report/", views.print_report, name="print_report"),
    # path("generate_pdf/", views.generate_pdf_new, name="generate_pdf_new"),
    path("generate_pdf/", views.generate_pdf_new, name="generate_pdf_new"),



    # echo payment
]

med_test2_app/urls.py
from turtle import heading
from django.urls import path

from med_test2_app.models import Med_test2_1_report, Med_test2_2_report, Med_test2_3_report, Med_test2_4_report, Med_test2_5_report
from med_test2_app.views import Create, Read, Update, Validate, Pdf

from . import views

app_name='med_test2_app'

urlpatterns = [
    path("", views.index, name="index"),

    path("create_1/", Create.as_view(report=Med_test2_1_report), name="Create_1"),
    path("create_2/", Create.as_view(report=Med_test2_2_report), name="Create_2"),
    path("create_3/", Create.as_view(report=Med_test2_3_report), name="Create_3"),
    path("create_4/", Create.as_view(report=Med_test2_4_report), name="Create_4"),
    path("create_5/", Create.as_view(report=Med_test2_5_report), name="Create_5"),

    path("read_1/", Read.as_view(report=Med_test2_1_report), name="Read_1"),
    path("read_2/", Read.as_view(report=Med_test2_2_report), name="Read_2"),
    path("read_3/", Read.as_view(report=Med_test2_3_report), name="Read_3"),
    path("read_4/", Read.as_view(report=Med_test2_4_report), name="Read_4"),
    path("read_5/", Read.as_view(report=Med_test2_5_report), name="Read_5"),

    path("update_1/", Update.as_view(report=Med_test2_1_report), name="Update_1"),
    path("update_2/", Update.as_view(report=Med_test2_2_report), name="Update_2"),
    path("update_3/", Update.as_view(report=Med_test2_3_report), name="Update_3"),
    path("update_4/", Update.as_view(report=Med_test2_4_report), name="Update_4"),
    path("update_5/", Update.as_view(report=Med_test2_5_report), name="Update_5"),

    path("validate_1/", Validate.as_view(report=Med_test2_1_report), name="Validate_1"),
    path("validate_2/", Validate.as_view(report=Med_test2_2_report), name="Validate_2"),
    path("validate_3/", Validate.as_view(report=Med_test2_3_report), name="Validate_3"),
    path("validate_4/", Validate.as_view(report=Med_test2_4_report), name="Validate_4"),
    path("validate_5/", Validate.as_view(report=Med_test2_5_report), name="Validate_5"),

    path("pdf_1/", Pdf.as_view(report=Med_test2_1_report, heading="USG ABDOMEN"), name="Pdf_1"),
    path("pdf_2/", Pdf.as_view(report=Med_test2_2_report, heading="USG BREAST"), name="Pdf_2"),
    path("pdf_3/", Pdf.as_view(report=Med_test2_3_report, heading="USG PELVIS"), name="Pdf_3"),
    path("pdf_4/", Pdf.as_view(report=Med_test2_4_report, heading="USG KUB"), name="Pdf_4"),
    path("pdf_5/", Pdf.as_view(report=Med_test2_5_report, heading="DOPPLER LOWER LIMB"), name="Pdf_5"),



]

patient_app/urls.py
from django.urls import path

from . import views

app_name="patient_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create_patient, name="create_patient"),
    path("read/", views.read_patient, name="read_patient"),
    path("update/", views.update_patient, name="update_patient"),
    # path("payment/", views.payment, name="payment"),
    path("print_report/", views.print_report, name="print_report"),



    # Echo payment
]

patient_app/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone

# from med_test1_app.models import Echo_report, Echo_payment
from med_test1_app.models import Med_test1_report

# class Constant(models.Model):
#     name = models.CharField(max_length=200, primary_key=True)
#     value=models.IntegerField()

class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    # id=models.CharField(max_length=200, primary_key=True)
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    mob_no=models.CharField(max_length=10, null=True)
    address=models.CharField(max_length=200, null=True)
    med_test1_report=models.OneToOneField(Med_test1_report, on_delete=models.CASCADE, null=True, related_name='med_test1_report')
    created_date = models.DateField(default=timezone.now)
    created_time = models.TimeField(default=timezone.now)

    ## tests
    med_test1=models.BooleanField(default=False)
    med_test2_1=models.BooleanField(default=False)
    med_test2_2=models.BooleanField(default=False)
    med_test2_3=models.BooleanField(default=False)
    med_test2_4=models.BooleanField(default=False)
    med_test2_5=models.BooleanField(default=False)
    


# class Receipt(models.Model):
#     # id=models.CharField(max_length=200, primary_key=True)
#     id=models.AutoField(primary_key=True)
#     patient=models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='receipt')
#     med_test1=models.IntegerField(null=True) # medical test 1
#     med_test2=models.IntegerField(null=True) # medical test 2
#     med_test3=models.IntegerField(null=True) # medical test 3
#     med_test4=models.IntegerField(null=True) # medical test 4
#     done_by=models.CharField(max_length=200, null=True)
#     created_date=models.DateField(default=timezone.now)
#     created_time=models.TimeField(default=timezone.now)

patient_app/views.py
import datetime
# import utils.utils as utils
from django.shortcuts import render, redirect, reverse

# Create your views here.
# from django.http import HttpResponse
from django.contrib import messages
# from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required

from django.contrib.auth.models import User, Permission

from .models import Patient
# CRUD


# index function
# @login_required(login_url='/login/')
# @permission_required('patient_app.view_patient')
def index(request):
    form_data=request.GET
    date=form_data.get('date', None)
    if date is None:
        date=datetime.date.today()
    try:
        p=Patient.objects.filter(created_date=date)
        return render(request, 'patient_app/index.html', {'patients':p})
    except Exception:
        messages.error(request, 'provide valid date')
        return redirect('index')

# @permission_required('patient_app.add_patient')
def create_patient(request):
    method=request.method
    match method:
        case 'GET':
            # send form for creating patient
            date=request.GET.get('date', None)
            if not date:
                date=datetime.date.today()
            p=Patient.objects.filter(created_date=date)
            return render(request, 'patient_app/create_patient.html', {'patients':p})
        case 'POST':
            # create patient in db
            form_data=request.POST
            name=form_data.get('name', None)
            age=form_data.get('age', None)
            gender=form_data.get('gender', None)
            mob_no=form_data.get('mob_no', None)
            address=form_data.get('address', None)
            try:
                p=Patient()
                # p=Patient.objects.create(name=name, age=age, gender=gender)
                # p.id=datetime.datetime.now().strftime('%Y%m%d%H%M%S')+str(Patient.objects.count()+1)
                p.name=name
                p.age=age
                p.gender=gender
                p.mob_no=mob_no
                p.address=address
                p.med_test1=form_data.get('med_test1', False)
                p.med_test2_1=form_data.get('med_test2_1', False)
                p.med_test2_2=form_data.get('med_test2_2', False)
                p.med_test2_3=form_data.get('med_test2_3', False)
                p.med_test2_4=form_data.get('med_test2_4', False)
                p.med_test2_5=form_data.get('med_test2_5', False)
                p.save()
                messages.success(request, 'Patient Saved successfully')
                return redirect(reverse('patient_app:create_patient'))
            except Exception:
                messages.error(request, 'Error creating patient')
                return redirect(reverse('patient_app:create_patient'))
        case default:
            messages.error(request, 'Method not allowed')
            return redirect(reverse('patient_app:create_patient'))



# @permission_required('patient_app.view_patient')
def read_patient(request):
    method=request.method
    match method:
        case 'GET':
            id=request.GET.get('id', None)
            p=Patient.objects.get(id=id)
            
            messages.success(request, 'patient fetched successfully')
            return render(request, 'patient_app/read_patient.html', {'patient':p})

        case default:
            messages.error(request, 'Method not allowed')
            return redirect('create_patient')


# @permission_required('patient_app.change_patient')
def update_patient(request):
    method=request.method
    match method:
        case 'GET':
            id=request.GET.get('id')
            try:
                p=Patient.objects.get(id=id)
                return render(request, 'patient_app/update_patient.html', {'patient':p})
            except Exception:
                messages.error(request, 'Patient not found or provide a valid id')
                return redirect('create_patient')
        
        case 'POST':
            form_data=request.POST
            id=form_data.get('id', None)


            p=Patient.objects.get(id=id)
 
            
            if not p.med_test1:
                p.med_test1=form_data.get('med_test1', False)
            if not p.med_test2_1:
                p.med_test2_1=form_data.get('med_test2_1', False)
            if not p.med_test2_2:
                p.med_test2_2=form_data.get('med_test2_2', False)
            if not p.med_test2_3:
                p.med_test2_3=form_data.get('med_test2_3', False)
            if not p.med_test2_4:
                p.med_test2_4=form_data.get('med_test2_4', False)
            if not p.med_test2_5:
                p.med_test2_5=form_data.get('med_test2_5', False)

            # update attributes
            p.save()
            messages.success(request, 'Patient updated successfully')
            return redirect(f'/patient/read/?id={id}')
        case default:
            messages.error(request, 'Method not allowed')
            return redirect('create_patient')


# @permission_required('patient_app.delete_patient')
def delete_patient(request):
    '''
    delete Patient
    '''
    id=request.POST.get('id', None)
    if request.method=='POST':
        try:
            p=Patient.objects.get(id=id)
            p.delete()
            messages.success(request, 'Patient deleted successfully')
            return redirect('index')
        except Exception:
            messages.error(request, 'Patient not found or provide a valid id')
            return redirect('index')
        

    else:
        messages.error(request, 'Method not allowed')
        return render(request, 'error.html')


       



def print_report(request):
    form_data=request.GET
    date=form_data.get('date', None)
    if date is None:
        date=datetime.date.today()
    patients=Patient.objects.all()
    return render(request, 'patient_app/print_report.html', {'patients':patients})

patient_app/templates/patient_app/create_patient.html
<!DOCTYPE html>
<html>

<head>
    <title>Create Patient</title>
    {% include 'include.html' %}

</head>

<body>
    {% include 'navbar.html' %}



    <div class="card container my-4">
        <div class="card-header">Register Patient</div>
        <div class="card-body">

            <form action="{% url 'patient_app:create_patient' %}" method="post">
                {% csrf_token %}
                <!-- Input type text -->
                <div class="form-group mb-2">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" name="name" id="name" placeholder="placeholder" required>
                </div>

                <!-- Input text grid -->
                <div class="form-group">
                    <div class="row mb-2">
                        <div class="col">
                            <label>Age</label>
                            <input type="number" name="age" id="age" class="form-control" placeholder="placeholder 1">
                        </div>
                        <div class="col">
                            <label for="select_id_4">Gender</label>
                            <select name="gender" class="form-select" aria-label="Default select example">
                                <option value="Male" selected>Male</option>
                                <option value="Female">Female</option>

                            </select>
                        </div>
                        <div class="col">
                            <label>Mobile No.</label>
                            <input type="text" class="form-control" name="mob_no" id="mob_no" placeholder="placeholder">
                        </div>
                        <div class="col">

                        </div>

                    </div>

                </div>
                <div class="form-group mb-2">
                    <input name="med_test1" class="form-check-input" type="checkbox" value="True" id="">
                    <label class="form-check-label" for="flexCheckDefault">
                        Echocardiography
                    </label>
                    <input name="med_test2_1" class="form-check-input" type="checkbox" value="True" id="">
                    <label class="form-check-label" for="flexCheckDefault">
                        USG ABDOMEN
                    </label>
                    <input name="med_test2_2" class="form-check-input" type="checkbox" value="True" id="">
                    <label class="form-check-label" for="flexCheckDefault">
                        USG BREAST
                    </label>
                    <input name="med_test2_3" class="form-check-input" type="checkbox" value="True" id="">
                    <label class="form-check-label" for="flexCheckDefault">
                        USG PELVIS
                    </label>
                    <input name="med_test2_4" class="form-check-input" type="checkbox" value="True" id="">
                    <label class="form-check-label" for="flexCheckDefault">
                        USG KUB
                    </label>
                    <input name="med_test2_5" class="form-check-input" type="checkbox" value="True" id="">
                    <label class="form-check-label" for="flexCheckDefault">
                        DOPPLER LOWER LIMB
                    </label>
                </div>
                <div class="form-outline mb-2">
                    <label class="form-label" for="textAreaExample">Address</label>
                    <textarea name="address" class="form-control" id="textAreaExample1" rows="4"></textarea>


                </div>



                <button type="submit" class="btn btn-primary" name="button_id_5" id="button_id_5">submit</button>
            </form>


        </div>
    </div>

    {% include 'patient_app/patients_table.html' %}


</body>

</html>

patient_app/templates/patient_app/create_patient_form.html
<div class="card container my-4">
    <div class="card-header">Register Patient</div>
    <div class="card-body">

        <form action="{% url 'patient_app:create_patient' %}" method="post">
            {% csrf_token %}
            <!-- Input type text -->
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="placeholder" required>
            </div>

            <!-- Input text grid -->
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label>Age</label>
                        <input type="number" name="age" id="age" class="form-control" placeholder="placeholder 1">
                    </div>
                    <div class="col">
                        <label for="select_id_4">Select</label>
                        <select class="custom-select" name="gender" id="gender">
                            <option value="male">Male</option>
                            <option value="female">Female</option>

                        </select>
                    </div>

                </div>
            </div>



            <button type="submit" class="btn btn-primary" name="button_id_5" id="button_id_5">submit</button>
        </form>


    </div>
</div>

patient_app/templates/patient_app/index.html
{% include 'include.html' %}

<!-- {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %} -->

{% include 'navbar.html' %} {% include 'messages.html' %}

<div class="container bg-secondary-subtle p-4">
    <form action="/patient" method="get">
        <input type="date" name="date" onchange="this.form.submit()" />
    </form>
    <table class="table table-secondary">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Age</th>
                <th scope="col">Gender</th>
            </tr>
        </thead>
        <tbody>
            {% for p in patients %}

            {% if p.med_test1 %}

            <tr class="">
                <th scope="row">{{p.id}}</th>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>

                {% if p.med_test1_report and p.med_test1_report.validated_by %}
                <td>
                    <form action="{% url 'med_test1_app:read_med_test1_report' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">View Echo</button>
                    </form>
                </td>
                {% elif p.med_test1_report %}
                <td>
                    <form action="{% url 'med_test1_app:read_med_test1_report' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Validate Echo</button>
                    </form>
                </td>
                {% else %}
                <td>
                    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Echo Template</button>
                    </form>
                </td>
                {% endif %}


            </tr>
            {% endif %}

            {% if p.med_test2_1 %}
            <tr class="">
                <th scope="row">{{p.id}}</th>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>

                {% if p.med_test2_1_report and p.med_test2_1_report.validated_by %}
                <td>
                    <form action="{% url 'med_test2_app:Read_1' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">View USG ABDOMEN</button>
                    </form>
                </td>
                {% elif p.med_test2_1_report %}
                <td>
                    <form action="{% url 'med_test2_app:Read_1' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Validate USG ABDOMEN</button>
                    </form>
                </td>
                {% else %}
                <td>
                    <form action="{% url 'med_test2_app:Create_1' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">USG ABDOMEN Template</button>
                    </form>
                </td>
                {% endif %}


            </tr>
            {% endif %}

            {% if p.med_test2_2 %}
            <tr class="">
                <th scope="row">{{p.id}}</th>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>

                {% if p.med_test2_2_report and p.med_test2_2_report.validated_by %}
                <td>
                    <form action="{% url 'med_test2_app:Read_2' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">View USG BREAST</button>
                    </form>
                </td>
                {% elif p.med_test2_2_report %}
                <td>
                    <form action="{% url 'med_test2_app:Read_2' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Validate USG BREAST</button>
                    </form>
                </td>
                {% else %}
                <td>
                    <form action="{% url 'med_test2_app:Create_2' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">USG BREAST Template</button>
                    </form>
                </td>
                {% endif %}


            </tr>
            {% endif %}

            {% if p.med_test2_3 %}
            <tr class="">
                <th scope="row">{{p.id}}</th>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>

                {% if p.med_test2_3_report and p.med_test2_3_report.validated_by %}
                <td>
                    <form action="{% url 'med_test2_app:Read_3' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">View USG PELVIS</button>
                    </form>
                </td>
                {% elif p.med_test2_3_report %}
                <td>
                    <form action="{% url 'med_test2_app:Read_3' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Validate USG PELVIS</button>
                    </form>
                </td>
                {% else %}
                <td>
                    <form action="{% url 'med_test2_app:Create_3' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">USG PELVIS Template</button>
                    </form>
                </td>
                {% endif %}


            </tr>
            {% endif %}

            {% if p.med_test2_4 %}
            <tr class="">
                <th scope="row">{{p.id}}</th>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>

                {% if p.med_test2_4_report and p.med_test2_4_report.validated_by %}
                <td>
                    <form action="{% url 'med_test2_app:Read_4' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">View USG KUB</button>
                    </form>
                </td>
                {% elif p.med_test2_4_report %}
                <td>
                    <form action="{% url 'med_test2_app:Read_4' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Validate USG KUB</button>
                    </form>
                </td>
                {% else %}
                <td>
                    <form action="{% url 'med_test2_app:Create_4' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">USG KUB Template</button>
                    </form>
                </td>
                {% endif %}


            </tr>
            {% endif %}

            {% if p.med_test2_5 %}
            <tr class="">
                <th scope="row">{{p.id}}</th>
                <td>{{p.name}}</td>
                <td>{{p.age}}</td>
                <td>{{p.gender}}</td>

                {% if p.med_test2_5_report and p.med_test2_5_report.validated_by %}
                <td>
                    <form action="{% url 'med_test2_app:Read_5' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">View DOPPLER LOWER LIMB</button>
                    </form>
                </td>
                {% elif p.med_test2_5_report %}
                <td>
                    <form action="{% url 'med_test2_app:Read_5' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">Validate DOPPLER LOWER LIMB</button>
                    </form>
                </td>
                {% else %}
                <td>
                    <form action="{% url 'med_test2_app:Create_5' %}" method="get">
                        <input type="number" name="id" value="{{p.id}}" hidden />
                        <button class="btn btn-success" type="submit">DOPPLER LOWER LIMB Template</button>
                    </form>
                </td>
                {% endif %}


            </tr>
            {% endif %}

            

            {% endfor %}
        </tbody>
    </table>
</div>

patient_app/templates/patient_app/patient_all.html
{% include 'include.html' %}

{% include 'patient_app/patients_table.html' %}

patient_app/templates/patient_app/patients_table.html
<div class="container bg-secondary-subtle p-4">
    <table class="table table-secondary">
      <div class="md-2">
          <form id="date_form" action="{{ request.build_absolute_uri }}" method="get" class="d-flex" role="search">
              <input id="date_input" class="" type="date" onchange="this.form.submit()" name="date">
          </form>
      </div>
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Age</th>
                <th scope="col">Gender</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for p in patients %}
                
                <tr class="">
                    <th scope="row">{{p.id}}</th>
                    <td>{{p.name}}</td>
                    <td>{{p.age}}</td>
                    <td>{{p.gender}}</td>
                    <td>
                        <form action="{% url 'patient_app:read_patient' %}" method="get">
                            <input type="number" name="id" value="{{p.id}}" hidden>
                            <button class="btn btn-success" type="submit">Billing</button>
                        </form>
                    </td>
                
                </tr>
                
                
            {% endfor %}

        </tbody>
    </table>
</div>

patient_app/templates/patient_app/payment.html
{% include 'include.html' %}

{% include 'patient_app/patients_table.html' %}

patient_app/templates/patient_app/print_report.html
{% include 'include.html' %}
{% include 'navbar.html' %}

<div class="container">
    <div class="md-2">
        <form id="date_form" action="{{ request.build_absolute_uri }}" method="get" class="d-flex" role="search">
            <input id="date_input" class="" type="date" onchange="this.form.submit()" name="date">
        </form>
    </div>
    <table class="table ">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
        </thead>
        <tbody>
            {% for patient in patients %}
            {% if patient.med_test1_report %}
            <tr>
                <th scope="row">{{patient.id}}</th>
                <td>{{patient.name}}</td>
                <td>Echo</td>
                <td>
                    <form action="{% url 'med_test1_app:generate_pdf_new' %}" method="get">
                        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
                        <button class="btn btn-success" type="submit">Generate PDF</button>
                    </form>
                </td>
            </tr>
            {% endif %}

            {% if patient.med_test2_1_report %}
            <tr>
                <th scope="row">{{patient.id}}</th>
                <td>{{patient.name}}</td>
                <td>Echo</td>
                <td>
                    <form action="{% url 'med_test2_app:pdf' 1 %}" method="post">
                        {% csrf_token %}
                        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
                        <button class="btn btn-success" type="submit">Generate PDF</button>
                    </form>
                </td>
            </tr>
            
            {% endif %}

            {% endfor %}


        </tbody>
    </table>
</div>

patient_app/templates/patient_app/receipt.html
{{receipt}}