med_diag/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient_app.urls', namespace='patient_app')),
    path('echo/', include('med_test1_app.urls', namespace='med_test1_app')),
    path('us/', include('med_test2_app.urls', namespace='med_test2_app')),
    path('', include('user_app.urls', namespace='user_app')),
    # path('', include('authApp.urls')),
]

med_test2_app/urls.py
from turtle import heading
from django.urls import path

from med_test2_app.models import Med_test2_1_report, Med_test2_2_report, Med_test2_3_report, Med_test2_4_report, Med_test2_5_report
from med_test2_app.views import Create, Read, Update, Validate, Pdf

from . import views

app_name='med_test2_app'

urlpatterns = [
    path("", views.index, name="index"),

    path("create_1/", Create.as_view(report=Med_test2_1_report), name="Create_1"),
    path("create_2/", Create.as_view(report=Med_test2_2_report), name="Create_2"),
    path("create_3/", Create.as_view(report=Med_test2_3_report), name="Create_3"),
    path("create_4/", Create.as_view(report=Med_test2_4_report), name="Create_4"),
    path("create_5/", Create.as_view(report=Med_test2_5_report), name="Create_5"),

    path("read_1/", Read.as_view(report=Med_test2_1_report), name="Read_1"),
    path("read_2/", Read.as_view(report=Med_test2_2_report), name="Read_2"),
    path("read_3/", Read.as_view(report=Med_test2_3_report), name="Read_3"),
    path("read_4/", Read.as_view(report=Med_test2_4_report), name="Read_4"),
    path("read_5/", Read.as_view(report=Med_test2_5_report), name="Read_5"),

    path("update_1/", Update.as_view(report=Med_test2_1_report), name="Update_1"),
    path("update_2/", Update.as_view(report=Med_test2_2_report), name="Update_2"),
    path("update_3/", Update.as_view(report=Med_test2_3_report), name="Update_3"),
    path("update_4/", Update.as_view(report=Med_test2_4_report), name="Update_4"),
    path("update_5/", Update.as_view(report=Med_test2_5_report), name="Update_5"),

    path("validate_1/", Validate.as_view(report=Med_test2_1_report), name="Validate_1"),
    path("validate_2/", Validate.as_view(report=Med_test2_2_report), name="Validate_2"),
    path("validate_3/", Validate.as_view(report=Med_test2_3_report), name="Validate_3"),
    path("validate_4/", Validate.as_view(report=Med_test2_4_report), name="Validate_4"),
    path("validate_5/", Validate.as_view(report=Med_test2_5_report), name="Validate_5"),

    path("pdf_1/", Pdf.as_view(report=Med_test2_1_report, heading="USG ABDOMEN"), name="Pdf_1"),
    path("pdf_2/", Pdf.as_view(report=Med_test2_2_report, heading="USG BREAST"), name="Pdf_2"),
    path("pdf_3/", Pdf.as_view(report=Med_test2_3_report, heading="USG PELVIS"), name="Pdf_3"),
    path("pdf_4/", Pdf.as_view(report=Med_test2_4_report, heading="USG KUB"), name="Pdf_4"),
    path("pdf_5/", Pdf.as_view(report=Med_test2_5_report, heading="DOPPLER LOWER LIMB"), name="Pdf_5"),



]

med_test2_app/models.py
from pyexpat import model
from django.db import models
from django.utils import timezone
from patient_app.models import Patient

# Create your models here.


class Med_test2_1_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test2_1_report')
    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1=models.TextField(null=True)

    
class Med_test2_2_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    # patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test1_report')
    patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test2_2_report')

    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1=models.TextField(null=True)

class Med_test2_3_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    # patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test1_report')
    patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test2_3_report')

    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1=models.TextField(null=True)

class Med_test2_4_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    # patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test1_report')
    patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test2_4_report')

    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1=models.TextField(null=True)

class Med_test2_5_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    # patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test1_report')
    patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test2_5_report')

    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1=models.TextField(null=True)

med_test2_app/views.py
# from doctest import REPORT_CDIFF
# from typing import Self
from django.views import View

# from cgi import test
# from email import message
# from email.policy import default
from django.shortcuts import render, redirect, reverse, resolve_url
from django.utils.html import linebreaks
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required

from django.db.models import Q
from django.core.serializers import serialize
# Create your views here.

from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context

import json
from django.http import JsonResponse

from django.contrib import messages
import datetime
# from patient_app.models import Patient
from patient_app.models import Patient
# from symbol import arglist
from .models import Med_test2_1_report, Med_test2_2_report, Med_test2_3_report, Med_test2_4_report, Med_test2_5_report


from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, PageTemplate, Frame, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO


def index(request):
    return render(request, 'med_test2_app/index.html')


def create(request, n):
    if n==1:
        return create_med_test2_1_report(request)
    return HttpResponse('method not allowed.')
    

def read(request, n):
    if n==1:
        return read_med_test2_1_report(request)
    return HttpResponse('method not allowed.')

def update(request, n):
    if n==1:
        return update_med_test2_1_report(request)
    return HttpResponse("method not allowed")

def validate(request, n):
    if n==1:
        return validate_med_test2_1_report(request)
    return HttpResponse("method not allowed.")

def pdf(request, n):
    if n==1:
        return generate_pdf_med_test2_1_report(request)
    return HttpResponse("method not allowed.")




def get_read_url(self):
    if self.report==Med_test2_1_report:
        return reverse('med_test2_app:Read_1')+f"?id={self.id}"
    if self.report==Med_test2_2_report:
        return reverse('med_test2_app:Read_2')+f"?id={self.id}"
    if self.report==Med_test2_3_report:
        return reverse('med_test2_app:Read_3')+f"?id={self.id}"
    if self.report==Med_test2_4_report:
        return reverse('med_test2_app:Read_4')+f"?id={self.id}"
    if self.report==Med_test2_5_report:
        return reverse('med_test2_app:Read_5')+f"?id={self.id}"
def get_create_url(self):
    if self.report==Med_test2_1_report:
        return reverse('med_test2_app:Create_1')+f"?id={self.id}"
    if self.report==Med_test2_2_report:
        return reverse('med_test2_app:Create_2')+f"?id={self.id}"
    if self.report==Med_test2_3_report:
        return reverse('med_test2_app:Create_3')+f"?id={self.id}"
    if self.report==Med_test2_4_report:
        return reverse('med_test2_app:Create_4')+f"?id={self.id}"
    if self.report==Med_test2_5_report:
        return reverse('med_test2_app:Create_5')+f"?id={self.id}"


class Create(View):
    id=None
    report=Med_test2_1_report
    def get(self, request):
        self.id=request.GET.get('id', None)
        try:
            p=Patient.objects.get(id=self.id)
        except Exception:
            messages.error(request, 'patient not found')
            return redirect(reverse('patient_app:create_patient'))
        # if hasattr(p, self.report):
        #     messages.error(request, 'report already existed please update or take print')
        #     return redirect(reverse('med_test2_app:read_med_test2_1_report'))
        try:
            r=self.report.objects.get(patient=p)
            messages.error(request, 'report already existed please update or take print')
            return redirect(self.read_url())
        except Exception:
            return render(request, self.get_template(), {'patient':p})
    def post(self, request):
        self.id=request.POST.get('id', None)
        try:
            p=Patient.objects.get(id=self.id)
        except Exception:
            messages.error(request, 'patient not found')
            return redirect(reverse('patient_app:create_patient'))
        try:
            r=self.report.objects.get(patient=p)
            messages.error(request, 'report already existed please update or take print')
            return redirect(self.read_url())
        except Exception:
            r=self.report.objects.create(patient=p)
            try:
                latest_id=self.report.objects.latest('id').id
            except Exception:
                latest_id=0
            r.lab_no=latest_id+1
            r.t1=request.POST.get('t1', None)
            r.save()
            messages.success(request, 'report created successfully.')
            return redirect(self.read_url())
    def get_template(self):
        if self.report==Med_test2_1_report:
            return 'med_test2_app/create_med_test2_1_report.html'
        if self.report==Med_test2_2_report:
            return 'med_test2_app/create_med_test2_2_report.html'
        if self.report==Med_test2_3_report:
            return 'med_test2_app/create_med_test2_3_report.html'
        if self.report==Med_test2_4_report:
            return 'med_test2_app/create_med_test2_4_report.html'
        if self.report==Med_test2_5_report:
            return 'med_test2_app/create_med_test2_5_report.html'
        return 'error.html'
        # match self.report:
        #     case Med_test2_1_report:
        #         return 'med_test2_app/create_med_test2_1_report.html'
        #     case Med_test2_2_report:
        #         return 'med_test2_app/create_med_test2_2_report.html'
        #     case Med_test2_3_report:
        #         return 'med_test2_app/create_med_test2_3_report.html'
        #     case Med_test2_4_report:
        #         return 'med_test2_app/create_med_test2_4_report.html'
        #     case Med_test2_5_report:
        #         return 'med_test2_app/create_med_test2_5_report.html'
        #     case _:
        #         return 'error.html'

    def read_url(self):
        if self.report==Med_test2_1_report:
            return reverse('med_test2_app:Read_1')+f"?id={self.id}"
        if self.report==Med_test2_2_report:
            return reverse('med_test2_app:Read_2')+f"?id={self.id}"
        if self.report==Med_test2_3_report:
            return reverse('med_test2_app:Read_3')+f"?id={self.id}"
        if self.report==Med_test2_4_report:
            return reverse('med_test2_app:Read_4')+f"?id={self.id}"
        if self.report==Med_test2_5_report:
            return reverse('med_test2_app:Read_5')+f"?id={self.id}"

class Read(View):
    id=None
    report=Med_test2_1_report
    def get(self, request):
        self.id=request.GET.get('id', None)
        try:
            p=Patient.objects.get(id=self.id)
        except Exception:
            messages.error(request, 'patient not found')
            return redirect(reverse('patient_app:create_patient'))
        try:
            r=self.report.objects.get(patient=p)
            return render(request, self.get_template(), {'patient':p})
        except Exception:
            messages.error(request, 'report not found')
            return redirect(self.create_url())
    

    def get_template(self):
        if self.report==Med_test2_1_report:
            return 'med_test2_app/read_med_test2_1_report.html'
        if self.report==Med_test2_2_report:
            return 'med_test2_app/read_med_test2_2_report.html'
        if self.report==Med_test2_3_report:
            return 'med_test2_app/read_med_test2_3_report.html'
        if self.report==Med_test2_4_report:
            return 'med_test2_app/read_med_test2_4_report.html'
        if self.report==Med_test2_5_report:
            return 'med_test2_app/read_med_test2_5_report.html'
        return 'error.html'
    
    def create_url(self):
        if self.report==Med_test2_1_report:
            return reverse('med_test2_app:Create_1')+f"?id={self.id}"
        if self.report==Med_test2_2_report:
            return reverse('med_test2_app:Create_2')+f"?id={self.id}"
        if self.report==Med_test2_3_report:
            return reverse('med_test2_app:Create_3')+f"?id={self.id}"
        if self.report==Med_test2_4_report:
            return reverse('med_test2_app:Create_4')+f"?id={self.id}"
        if self.report==Med_test2_5_report:
            return reverse('med_test2_app:Create_5')+f"?id={self.id}"


class Update(View):
    id=None
    report=Med_test2_1_report
    def get(self, request):
        self.id=request.GET.get('id', None)
        try:
            p=Patient.objects.get(id=self.id)
        except Exception:
            messages.error(request, 'patient not found')
            return redirect(reverse('patient_app:create_patient'))
        try:
            r=self.report.objects.get(patient=p)
            return render(request, self.get_template(), {'patient':p})
        except Exception:
            messages.error(request, 'report not found')
            return redirect(get_create_url({'id':self.id, 'report':self.report}))
    def post(self, request):
        self.id=request.POST.get('id', None)
        try:
            p=Patient.objects.get(id=self.id)
        except Exception:
            messages.error(request, 'patient not found')
            return redirect(reverse('patient_app:create_patient'))
        try:
            r=self.report.objects.get(patient=p)
            r.t1=request.POST.get('t1', r.t1)
            r.save()
            messages.success(request, 'report updated successfully.')
            return redirect(get_read_url({'id':self.id, 'report':self.report}))
        except Exception:
            messages.error(request, 'report not found')
            return redirect(get_create_url({'id':self.id, 'report':self.report}))
    def get_template(self):
        if self.report==Med_test2_1_report:
            return 'med_test2_app/update_med_test2_1_report.html'

med_test2_app/templates/med_test2_app/create_med_test2_2_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Create_2' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows=""><p><strong>REPORT:</strong><br>&nbsp;</p><p><strong>RT BREAST:</strong><br>&nbsp;</p><p><strong>Fibroglandular tissue-</strong> normal<br><strong>Nipple areolar complex and retroareloar tissue-</strong> normal<br><strong>Fatty tissue-</strong> normal<br><strong>Retromammary area-</strong> normal<br><strong>RT AXILLA:</strong> Normal; no evidence of lymphademopathy<br><strong>LT BREAST:</strong><br><strong>Fibroglandular tissue-</strong> normal<br><strong>Nipple areolar complex and retroareloar tissue-</strong>normal<br><strong>Fatty tissue-</strong> normal<br><strong>Retromammary area-</strong> normal<br><strong>LT AXILLA:</strong> Normal; no evidence of lymphadenopathy<br>&nbsp;</p><p><strong>IMPRESSION:-</strong><br>&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/create_med_test2_3_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Create_3' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows=""><p><strong>Findings:</strong><br>1. Uterus<br>2. B/ladnexa<br>3. Urinary bladder<br>4. No e/o free fluid in peritoneal cavity<br>&nbsp;</p><p><strong>Impression:</strong></p><p>&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>

    
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/create_med_test2_4_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Create_4' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows=""><p><strong>REPORT:</strong></p><p><br><strong>Right kidney:</strong> Normal in size and echotexture. Corticomedullary differentiation is maintained.<br>No calculus or hydronephrosis noted.<br>&nbsp;</p><p><strong>Left kidney:</strong> Normal in size and echotexture. Corticomedullary differentiation is maintained. No calculus or hydronephrosis noted.<br>&nbsp;</p><p><strong>Urinary Bladder:</strong> Normally distended. No calculus, debris, mass or wall thickening noted.<br>&nbsp;</p><p><strong>Prostate/ Uterus:</strong> Normal size and echotexture.<br>No pelvis mass seen.<br>&nbsp;</p><p><strong>Impression:</strong></p><p>&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>

    
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/read_med_test2_1_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<div>

    {{patient.med_test2_1_report.t1}}
</div>

<div>
    <form action="{% url 'med_test2_app:Pdf_1' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Generate PDF</button>
        
    </form>
</div>
<div>
    <form action="{% url 'med_test2_app:Update_1' %}" method="get">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Update</button>

    </form>
</div>

med_test2_app/templates/med_test2_app/read_med_test2_2_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<div class="container">

    {{patient.med_test2_2_report.t1|safe}}
    <div>
        <form action="{% url 'med_test2_app:Pdf_2' %}" method="post">
            {% csrf_token %}
            <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
            <button class="btn btn-success" type="submit">Print</button>
    
        </form>
    </div>
    <div>
        <form action="{% url 'med_test2_app:Update_2' %}" method="get">
            {% csrf_token %}
            <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
            <button class="btn btn-success" type="submit">Update</button>
    
        </form>
    </div>
</div>

med_test2_app/templates/med_test2_app/read_med_test2_3_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<div>

    {{patient.med_test2_3_report.t1}}
</div>

<div>
    <form action="{% url 'med_test2_app:Pdf_3' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Generate PDF</button>
        
    </form>
</div>
<div>
    <form action="{% url 'med_test2_app:Update_3' %}" method="get">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Update</button>

    </form>
</div>

med_test2_app/templates/med_test2_app/read_med_test2_4_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<div>

    {{patient.med_test2_4_report.t1}}
</div>

<div>
    <form action="{% url 'med_test2_app:Pdf_4' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Generate PDF</button>
        
    </form>
</div>
<div>
    <form action="{% url 'med_test2_app:Update_4' %}" method="get">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Update</button>

    </form>
</div>

med_test2_app/templates/med_test2_app/read_med_test2_5_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<div>

    {{patient.med_test2_5_report.t1}}
</div>

<div>
    <form action="{% url 'med_test2_app:Pdf_5' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Generate PDF</button>
        
    </form>
</div>
<div>
    <form action="{% url 'med_test2_app:Update_5' %}" method="get">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>
        <button class="btn btn-success" type="submit">Update</button>

    </form>
</div>

med_test2_app/templates/med_test2_app/update_med_test2_1_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Update_1' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows="">{{patient.med_test2_1_report.t1}}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/update_med_test2_2_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Update_2' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows="">{{patient.med_test2_2_report.t1}}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/update_med_test2_3_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Update_3' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows="">{{patient.med_test2_3_report.t1}}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/update_med_test2_4_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Update_4' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows="">{{patient.med_test2_4_report.t1}}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>

med_test2_app/templates/med_test2_app/update_med_test2_5_report.html
{% include "include.html" %}
{% include "navbar.html" %}
<body>
    <form action="{% url 'med_test2_app:Update_5' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1" class="form-control" id="med_test2_1_report" rows="">{{patient.med_test2_5_report.t1}}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js">
    </script>
    <script>
        ClassicEditor
        .create(document.querySelector('#med_test2_1_report'))
            .catch(error => {
                console.error(error);
            });
        
    </script>
</body>