med_diag/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient_app.urls', namespace='patient_app')),
    path('echo/', include('med_test1_app.urls', namespace='med_test1_app')),
    path('us/', include('med_test2_app.urls', namespace='med_test2_app')),
    path('', include('user_app.urls', namespace='user_app')),
    # path('', include('authApp.urls')),
]

patient_app/urls.py
from django.urls import path

from . import views

app_name="patient_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create_patient, name="create_patient"),
    path("read/", views.read_patient, name="read_patient"),
    path("update/", views.update_patient, name="update_patient"),
    # path("payment/", views.payment, name="payment"),
    path("print_report/", views.print_report, name="print_report"),



    # Echo payment
]

user_app/urls.py
from django.urls import path

from . import views

app_name='user_app'

urlpatterns = [
    path("", views.index, name="index"),
    path("user/create/", views.create_user, name="create_user"),
    path("user/read/", views.read_user, name="read_user"),
    path("user/update/", views.update_user, name="update_user"),
    path("user/delete/", views.delete_user, name="delete_user"),



    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("accounts/login/", views.login_user, name="login_user"),


    # path("user/receipt/", views.receipt, name="receipt"),
    # path("user/constant/", views.constant, name="constant"),
    

]

templates/footer.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

templates/include.html
{% load static %}

<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->

templates/index.html
<h1>
    index.html
</h1>

templates/login.html
{% include 'include.html' %}
{% include 'navbar.html' %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<body>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="/login/" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                <input type="text" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

templates/messages.html
{% include 'include.html' %}


{% for message in messages %}
<div role="alert" aria-live="assertive" aria-atomic="true" class="toast" data-autohide="false">
    <div class="toast-header">
      <img src="..." class="rounded mr-2" alt="...">
      <strong class="mr-auto">Bootstrap</strong>
      <small>11 mins ago</small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      {{message}}
    </div>
  </div>
{% endfor %}


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $('.toast').toast('show');
});
</script>

templates/navbar.html
{% include 'include.html' %}




<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'patient_app:create_patient' %}">Patient</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patient_app:index' %}">Report Entry</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patient_app:print_report' %}">Print Report</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'user_app:create_user' %}">Users</a></li>
                        {% comment %} <li><a class="dropdown-item" href="{% url 'user_app:receipt' %}">Receipts</a></li>
                        <li><a class="dropdown-item" href="{% url 'user_app:constant' %}">Constant</a></li> {% endcomment %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
                <li class="nav-item">
                    <form action="/logout/" method="post" class="d-flex" role="search">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit">Logout</button>
                    </form>
                </li>
                

            </ul>

            <div>
                {{user.username}}
            </div>


            <div>
                <form action="{% url 'patient_app:read_patient' %}" method="get" class="d-flex" role="search">
                    <input class="form-control me-2" type="number" placeholder="Search" aria-label="Search" name="id">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>

{% include 'footer.html' %}


{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" data-mdb-autohide="true" >
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
{% endif %}

templates/patient_detail.html
<div class="m-2">

    <table class="table table-borderless">
        <tbody>
            <tr>
                <th>ID No.</th>
                <td>{{patient.id}}</td>
                
                <th>Procedure Date</th>
                <td>{{patient.created_date}}/{{patient.created_time}}</td>
            </tr>
            <tr>
                <th>Patient Name </th>
                <td>{{patient.name}}</td>
                <th>Age/Sex </th>
                <td> {{patient.age}} Yr /{{patient.gender}} </td>
                
            </tr>
            <tr>
                <th>Mob No.</th>
                <td>{{patient.mob_no}}</td>
                
            </tr>
            

        </tbody>

    </table>
</div>

templates/success.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}