med_diag/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient_app.urls', namespace='patient_app')),
    path('echo/', include('med_test1_app.urls', namespace='med_test1_app')),
    path('us/', include('med_test2_app.urls', namespace='med_test2_app')),
    path('', include('user_app.urls', namespace='user_app')),
    # path('', include('authApp.urls')),
]

med_test1_app/urls.py
from django.urls import path

from . import views

app_name='med_test1_app'

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create_med_test1_report, name="create_med_test1_report"),
    path("read/", views.read_med_test1_report, name="read_med_test1_report"),
    path("update/", views.update_med_test1_report, name="update_med_test1_report"),
    path("delete/", views.delete_med_test1_report, name="delete_med_test1_report"),
    path('validate/', views.validate, name='validate'),
    path('test/', views.test, name='test'),

    path("print_report/", views.print_report, name="print_report"),
    # path("generate_pdf/", views.generate_pdf_new, name="generate_pdf_new"),
    path("generate_pdf/", views.generate_pdf_new, name="generate_pdf_new"),



    # echo payment
]

med_test1_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

# from patient_app.models import Patient

# many to one relation -> one patient may have many reports but one report will have only one patient

class Med_test1_report(models.Model):
    """
    Model representing an Echo report.
    """
    # patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='EchoReport')
    # patient=models.OneToOneField(Patient, on_delete=models.CASCADE, related_name='med_test1_report')
    id=models.AutoField(primary_key=True)
    reffered_by=models.CharField(max_length=200, null=True)
    validated_by=models.CharField(max_length=200, null=True)
    created_date=models.DateField(default=timezone.now)
    lab_no=models.IntegerField(null=True)

    t1_1=models.TextField(null=True)
    
    t1=models.CharField(max_length=200, null=True)
    t2=models.CharField(max_length=200, null=True)
    t3=models.CharField(max_length=200, null=True)
    t4=models.CharField(max_length=200, null=True)
    t5=models.CharField(max_length=200, null=True)
    t6=models.CharField(max_length=200, null=True)
    t7=models.CharField(max_length=200, null=True)
    t8=models.CharField(max_length=200, null=True)
    t9=models.CharField(max_length=200, null=True)
    t10=models.CharField(max_length=200, null=True)
    t11=models.CharField(max_length=200, null=True)
    t12=models.CharField(max_length=200, null=True)
    t13=models.CharField(max_length=200, null=True)
    t14=models.CharField(max_length=200, null=True)
    t14_1=models.CharField(max_length=200, null=True)
    t14_2=models.CharField(max_length=200, null=True)
    t14_3=models.CharField(max_length=200, null=True)
    t14_4=models.CharField(max_length=200, null=True)
    t15=models.CharField(max_length=200, null=True)
    t15_1=models.CharField(max_length=200, null=True)
    t15_2=models.CharField(max_length=200, null=True)
    t16=models.CharField(max_length=200, null=True)
    t17=models.CharField(max_length=200, null=True)
    t18=models.CharField(max_length=200, null=True)
    t19=models.CharField(max_length=200, null=True)
    t20=models.CharField(max_length=200, null=True)
    t21=models.CharField(max_length=200, null=True)
    t22=models.CharField(max_length=200, null=True)
    t23=models.CharField(max_length=200, null=True)
    t23_1=models.CharField(max_length=200, null=True)
    t23_2=models.CharField(max_length=200, null=True)
    t23_3=models.CharField(max_length=200, null=True)
    t23_4=models.CharField(max_length=200, null=True)
    t23_5=models.CharField(max_length=200, null=True)
    t24=models.CharField(max_length=200, null=True)
    t24_1=models.CharField(max_length=200, null=True)
    t24_2=models.CharField(max_length=200, null=True)
    t25=models.CharField(max_length=200, null=True)
    t26=models.CharField(max_length=200, null=True)
    t27=models.CharField(max_length=200, null=True)
    t27_1=models.CharField(max_length=200, null=True)
    t27_2=models.CharField(max_length=200, null=True)
    t27_3=models.CharField(max_length=200, null=True)
    t27_4=models.CharField(max_length=200, null=True)
    t27_5=models.CharField(max_length=200, null=True)
    t27_6=models.CharField(max_length=200, null=True)
    t28=models.CharField(max_length=200, null=True)
    t28_1=models.CharField(max_length=200, null=True)
    t28_2=models.CharField(max_length=200, null=True)
    t28_3=models.CharField(max_length=200, null=True)
    t29=models.CharField(max_length=200, null=True)
    t30=models.CharField(max_length=200, null=True)
    t30_1=models.CharField(max_length=200, null=True)
    t30_2=models.CharField(max_length=200, null=True)
    t31=models.CharField(max_length=200, null=True)
    t31_1=models.CharField(max_length=200, null=True)
    t31_2=models.CharField(max_length=200, null=True)
    t31_3=models.CharField(max_length=200, null=True)
    t31_4=models.CharField(max_length=200, null=True)
    t32=models.CharField(max_length=200, null=True)
    t33=models.CharField(max_length=200, null=True)
    t34=models.CharField(max_length=200, null=True)
    t34_1=models.CharField(max_length=200, null=True)
    t34_2=models.CharField(max_length=200, null=True)
    t35=models.CharField(max_length=200, null=True)
    t35_1=models.CharField(max_length=200, null=True)
    t35_2=models.CharField(max_length=200, null=True)
    t36=models.CharField(max_length=200, null=True)
    t36_1=models.CharField(max_length=200, null=True)
    t36_2=models.CharField(max_length=200, null=True)
    t36_3=models.CharField(max_length=200, null=True)
    # t37=models.CharField(max_length=200, null=True)
    t37=models.TextField(null=True)
    # t38=models.CharField(max_length=200, null=True)
    t38=models.TextField(null=True)
    # t39=models.CharField(max_length=200, null=True)
    t39=models.TextField(null=True)
    


# class Echo_payment(models.Model):
#     # patient=models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='echo_payment')
#     created_date = models.DateField(default=timezone.now)
#     created_time = models.TimeField(default=timezone.now)
#     done_by=models.CharField(max_length=200, null=True)
#     amount=models.IntegerField(null=True)

med_test1_app/views.py
from django.shortcuts import render, redirect, reverse
from django.conf import settings
import os
from django.utils.html import linebreaks
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required

from django.db.models import Q
from django.core.serializers import serialize
# Create your views here.

from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context

import json
from django.http import JsonResponse

from django.contrib import messages
import datetime
# from patient_app.models import Patient
from patient_app.models import Patient
from .models import Med_test1_report

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors, utils
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, PageTemplate, Frame, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO



# @permission_required('patient_app.view_patient')
def index(request):
    return redirect(reverse('patient_app:create_patient'))
    # print(request.user.get_all_permissions())
    form_data=request.GET
    date=form_data.get('date', None)
    if date==None:
        date=datetime.date.today()

    
    # receipts=Receipt.objects.filter(Q(created_date=date) & ~Q(med_test1__isnull=True))
    # serialised_data=serialize('json', receipts)
    # return JsonResponse(serialised_data, safe=False)
    
    return render(request, 'med_test1_app/index.html')
    

# @permission_required('med_test1_app.add_echoreport')
# def create_med_test1_report(request):
def create_med_test1_report(request):

    if request.method=='GET':
        id=request.GET.get('id', None)
        try:
            p=Patient.objects.get(id=id)
        except Exception:
            messages.error(request, 'Patient not found')
            return redirect(reverse('patient_app:create_patient'))
        if p.med_test1_report:
            messages.error(request, 'report already existed please update or take print')
            return redirect(reverse('patient_app:read_patient')+f'?id={id}')
        return render(request, 'med_test1_app/create.html', {'patient':p})
        # return render(request, 'med_test1_app/create_med_test1_report.html', {'patient':p})


    elif request.method=='POST':

        # return render(request, 'med_test1_app/helper/read.html', {'t1_1':request.POST.get('t1_1', None)})
        # create echo report with id
        form_data=request.POST
        # print(form_data)
        # return render(request, 'error.html', {'form_data':form_data})
        id=form_data.get('id', None)
        try:
            p=Patient.objects.get(id=id)
        except Exception:

            messages.error(request, 'Patient not found')
            return render(request, 'error.html')
        if p.med_test1_report:
            messages.error(request, 'report already existed please update or take print')
            return redirect(reverse('patient_app:read_patient')+f'?id={id}')
        

        
        latest_id=Med_test1_report.objects.latest('id')
        echo=Med_test1_report()
        echo.lab_no=latest_id.id+1
        # echo.validated_by=request.user.username

        echo.t1_1=form_data.get('t1_1', None)

        echo.t1=form_data.get('t1', None)
        echo.t2=form_data.get('t2', None)
        echo.t3=form_data.get('t3', None)
        echo.t4=form_data.get('t4', None)
        echo.t5=form_data.get('t5', None)
        echo.t6=form_data.get('t6', None)
        echo.t7=form_data.get('t7', None)
        echo.t8=form_data.get('t8', None)
        echo.t9=form_data.get('t9', None)
        echo.t10=form_data.get('t10', None)
        echo.t11=form_data.get('t11', None)
        echo.t12=form_data.get('t12', None)
        echo.t13=form_data.get('t13', None)

        # RWMA
        echo.t14=form_data.get('t14', None)
        # if echo.t14!='Absent':
        echo.t14_1=', '.join(form_data.getlist('t14_1', None)) if form_data.getlist('t14_1', None) else ''
        echo.t14_2=', '.join(form_data.getlist('t14_2', None)) if form_data.getlist('t14_2', None) else ''
        echo.t14_3=', '.join(form_data.getlist('t14_3', None)) if form_data.getlist('t14_3', None) else ''
        echo.t14_4=', '.join(form_data.getlist('t14_4', None)) if form_data.getlist('t14_4', None) else ''

        # mitral morphology
        echo.t15=', '.join(form_data.getlist('t15', None)) if form_data.getlist('t15', None) else ''
        if 'Normal' in echo.t15:
            echo.t15='Normal'

        # if echo.t15 != 'Normal':
        echo.t15_1=', '.join(form_data.getlist('t15_1', None)) if form_data.getlist('t15_1', None) else ''
        echo.t15_2=', '.join(form_data.getlist('t15_2', None)) if form_data.getlist('t15_2', None) else ''
        
        echo.t16=form_data.get('t16', None)
        echo.t17=form_data.get('t17', None)
        echo.t18=form_data.get('t18', None)
        echo.t19=form_data.get('t19', None)
        echo.t20=form_data.get('t20', None)
        echo.t21=form_data.get('t21', None)
        echo.t22=form_data.get('t22', None)

        # Mitral Stenosis
        echo.t23=form_data.get('t23', None)
        # if echo.t23 != 'Absent':
        echo.t23_1=form_data.get('t23_1', '')
        echo.t23_2=form_data.get('t23_2', '')
        echo.t23_3=form_data.get('t23_3', '')
        echo.t23_4=form_data.get('t23_4', '')
        echo.t23_5=form_data.get('t23_5', '')

        # Mitral Regurgitation
        echo.t24=form_data.get('t24', None)
        echo.t24_1=form_data.get('t24_1', None)
        echo.t24_2=form_data.get('t24_2', None)

        # Aortic Morphology
        echo.t25=', '.join(form_data.getlist('t25', None)) if form_data.getlist('t25', None) else ''
        echo.t25.replace('Abnormal', '')

        echo.t26=form_data.get('t26', None)

        # Aortic stenosis
        echo.t27=form_data.get('t27', None)
        echo.t27_1=form_data.get('t27_1', None)
        echo.t27_2=form_data.get('t27_2', None)
        echo.t27_3=form_data.get('t27_3', None)
        echo.t27_4=form_data.get('t27_4', None)
        echo.t27_5=form_data.get('t27_5', None)
        echo.t27_6=form_data.get('t27_6', None)

        # Aortic regurgitation
        echo.t28=form_data.get('t28', None)
        echo.t28_1=form_data.get('t28_1', None)
        echo.t28_2=form_data.get('t28_2', None)
        echo.t28_3=form_data.get('t28_3', None)

        # TRISCUPID Morphology
        echo.t29=', '.join(form_data.getlist('t29', None)) if form_data.getlist('t29', None) else ''
        echo.t29.replace('Abnormal', '')

        # Triscupid Stenosis
        echo.t30=form_data.get('t30', None)
        echo.t30_1=form_data.get('t30_1', None)
        echo.t30_2=form_data.get('t30_2', None)

        # Triscupid Regurgitation
        echo.t31=form_data.get('t31', None)
        echo.t31_1=form_data.get('t31_1', None)
        echo.t31_2=form_data.get('t31_2', None)
        echo.t31_3=form_data.get('t31_3', None)
        echo.t31_4=form_data.get('t31_4', None)

        # Pulmonary Morphology
        echo.t32=', '.join(form_data.getlist('t32', None)) if form_data.getlist('t32', None) else ''
        echo.t32.replace('Abnormal', '')

        echo.t33=form_data.get('t33', None)

        # Pulmonary Stenosis
        echo.t34=form_data.get('t34', None)
        echo.t34_1=form_data.get('t34_1', None)
        echo.t34_2=form_data.get('t34_2', None)

        # Pulmonary Regurgitation
        echo.t35=form_data.get('t35', None)
        echo.t35_1=form_data.get('t35_1', None)
        echo.t35_2=form_data.get('t35_2', None)

        # Pulmonary Artery
        echo.t36=form_data.get('t36', None)
        echo.t36_1=form_data.get('t36_1', None)
        echo.t36_2=form_data.get('t36_2', None)
        echo.t36_3=form_data.get('t36_3', None)

        echo.t37=form_data.get('t37', "")
        echo.t38=form_data.get('t38', "")
        echo.t39=form_data.get('t39', "")

        echo.save()
        p.med_test1_report=echo
        p.save()

        messages.success(request, 'report created successfully.')
        return redirect(reverse('med_test1_app:read_med_test1_report')+f'?id={id}')
    else:
        # print('method not allowed')
        messages.error(request, 'Method not allowed')
        return render(request, 'error.html')



# @permission_required('med_test1_app.view_echoreport')
# def read_med_test1_report(request):
def read_med_test1_report(request):
    if request.method=='GET':
        id=request.GET.get('id')
        try:
            p=Patient.objects.get(id=id)
        except Exception:
            messages.error(request, 'Patient not found')
            return redirect(reverse('patient_app:create_patient'))
        if p.med_test1_report:
            # print(p.med_test1_report.t37)
            if p.med_test1_report.t1_1:
                return render(request, 'med_test1_app/helper/read.html', {'patient':p})
            return render(request, 'med_test1_app/read_med_test1_report.html', {'patient':p})
        else:
            messages.error(request, 'report does not found')
            return redirect(reverse('patient_app:read_patient')+f'?id={id}')
    else:
        messages.error(request, 'Method not allowed')
        return render(request, 'error.html')
        


# @permission_required('med_test1_app.change_echoreport')

def update_med_test1_report(request):
    if request.method=='GET':
        id=request.GET.get('id')
        try:
            p=Patient.objects.get(id=id)
        except Exception:
            messages.error(request, 'patient not found')
            return redirect(reverse('patient_app:create_patient'))
        if p.med_test1_report:
            if p.med_test1_report.t1_1:
                return render(request, 'med_test1_app/helper/update.html', {'patient':p})
            return render(request, 'med_test1_app/update_med_test1_report.html', {'patient':p})
        else:

med_test1_app/templates/med_test1_app/helper/read.html
{% include "include.html" %}
{% include "navbar.html" %}

<div class="container">
    {{patient.med_test1_report.t1_1|safe}}
</div>
<div class="container">
    {% if patient.med_test1_report and patient.med_test1_report.validated_by %}
        <div>
            <form action="{% url 'med_test1_app:generate_pdf_new' %}" method="get">
                <input type="number" name="id" id="id" hidden value="{{patient.id}}">
                <button type="submit" class="btn btn-primary" id="generate-pdf">Generate PDF</button>
            </form>
        </div>
        {% else %}
        <div class="row text-center">
            <div class="col">

                <form action="{% url 'med_test1_app:validate' %}" method="post">
                    {% csrf_token %}
                    <input type="number" name="id" id="id" hidden value="{{patient.id}}">
                    <button type="submit" class="btn btn-primary" id="generate-pdf">Validate</button>
                </form>
            </div>
            
        </div>

        {% endif %}
        <div class="col">

            <form action="{% url 'med_test1_app:update_med_test1_report' %}" method="get">
                <input type="number" name="id" id="id" hidden value="{{patient.id}}">
                <button type="submit" class="btn btn-primary" id="generate-pdf">Update</button>
            </form>
        </div>
</div>

med_test1_app/templates/med_test1_app/helper/t1_1.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_1" rows=""><p><strong>Remarks:</strong></p><p>&nbsp;</p><p>SITUS SOLITUS<br>LEVOCARDIA<br>ALL FOUR PULMONARY VEINS DRAINING INTO LA</p><p>IVC/SVC DRAINING INTO RA<br>NRGA&nbsp;</p><p>AV-VA CONCORDANCE<br>MORPHOLOGICALLY NORMAL VALVES<br>INTACT IAS &amp; IVS<br>NORMAL BIVENTRICULAR SYSTOLIC FUNCTION</p><p>NO PDA / COARCTATION OF AORTA<br>NO PERICARDIAL EFFUSION / VEGETATION</p><p>&nbsp;</p><p><strong>Impression:</strong></p><p>NORMAL STUDY.</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>

med_test1_app/templates/med_test1_app/helper/t1_10.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_10" rows=""><p><strong>Remarks:</strong></p><p>&nbsp;</p><p>SITUS SOLITUS<br>LEVOCARDIA<br>ALL FOUR PULMONARY VEINS DRAINING INTO LA<br>IVC/SVC DRAINING INTO RA<br>NRGA&nbsp;<br>AV-VA CONCORDANCE<br>APICAL DISPLACEMENT OF TRICUSPID VALVE, DISTANCE BETWEEN ATL AND AML ATTACHMENT IS 26mm. (RA + ATRIALISED RV- 54 cmsq, RV- 24 cmsq, LA- 11.4 cmsq, LV- 19.7 cmsq, ATRIALISED RV- 29 cmsq)<br>21 mm OSTIUM SECUNDUM ASD WITH BIDIRECTIONAL SHUNT&nbsp;<br>MPA- 15.2 mm, RPA- 8.8mm LPA- 9.3mm<br>SEVERE LOW PRESSURE TR (TRJV- 205 cm/sec, RVSP- 14mmHg)<br>IVS INTACT<br>NO PDA / COARCTATION OF OF AORTA<br>&nbsp;</p><p><strong>Impression:</strong></p><p>&nbsp;</p><p>CONGENITAL CYANOTIC HEART DISEASE<br>EBSTEIN’S ANOMALY WITH OSTIUM SECUNDUM ASD WITH BIDIRECTIONAL SHUNT&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>

med_test1_app/templates/med_test1_app/helper/t1_11.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_11" rows=""></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>

med_test1_app/templates/med_test1_app/helper/t1_2.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_2" rows=""><p><strong>Remarks:</strong></p><p>&nbsp;</p><p>SITUS SOLITUS<br>LEVOCARDIA<br>ALL FOUR PULMONARY VEINS DRAINING INTO LA<br>IVC/SVC DRAINING INTO RA<br>NRGA<br>AV-VA CONCORDANCE<br>mm OSTIUM SECUNDUM ASD WITH LEFT TO RIGHT SHUNT<br>IVS INTACT<br>MORPHOLOGICALLY NORMAL VALVES<br>NORMAL BIVENTRICULAR SYSTOLIC FUNCTION<br>NO PDA, NO COARCTATION OF AORTA<br>NO VEGETATION, NO PERICARDIAL EFFUSION<br>&nbsp;</p><p><strong>Impression:</strong></p><p>&nbsp;</p><p>ACYANOTIC CONGENITAL HEART DISEASE<br>LARGE OSTIUM SECUNDUM ASD WITH LEFT TO RIGHT SHUNT.</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>

med_test1_app/templates/med_test1_app/helper/t1_3.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_3" rows=""><p><strong>Remarks:</strong></p><p>&nbsp;</p><p>SITUS SOLITUS<br>LEVOCARDIA<br>TWO WELL DEVELOPED ATRIA PRESENT<br>TWO WELL DEVELOPED VENTRICLES PRESENT<br>ALL FOUR PULMONARY VEINS DRAINING INTO LA<br>IVC/SVC DRAINING INTO RA<br>AV-VA CONCORDANCE<br>NRGA<br>IAS INTACT<br>mm VSD WITH LEFT TO RIGHT SHUNT<br>MORPHOLOGICALLY NORMAL VALVES<br>NORMAL BIVENTRICULAR SYSTOLIC FUNCTION<br>NO PDA, NO COARCTATION OF AORTA<br>NO PERICARDIAL EFFUSION / VEGETATION<br>&nbsp;</p><p><strong>Impression:</strong></p><p>&nbsp;</p><p>ACYANOTIC CONGENITAL HEART DISEASE<br>LARGE VSD WITH LEFT TO RIGHT SHUNT.<br>&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>

med_test1_app/templates/med_test1_app/helper/t1_4.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_4" rows=""><p><strong>Remarks:</strong></p><p>&nbsp;</p><p>SITUS SOLITUS<br>LEVOCARDIA<br>TWO WELL DEVELOPED ATRIA PRESENT<br>TWO WELL DEVELOPED VENTRICLES PRESENT<br>ALL FOUR PULMONARY VEINS DRAINING INTO LA<br>IVC/SVC DRANING INTO RA<br>NRGA<br>AV-VA CONCORDANCE<br>MORPHOLOGICALLY NORMAL VALVES<br>IAS/IVS INTACT<br>mm PDA WITH LEFT TO RIGHT SHUNT<br>NORMAL BIVENTRICULAR SYSTOLIC FUNCTION<br>NO PAH<br>NO COARCTATION OF AORTA<br>NO VEGETATION, NO PERICARDIAL EFFUSION<br>&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>

med_test1_app/templates/med_test1_app/helper/t1_5.html
<div>
    <form action="{% url 'med_test1_app:create_med_test1_report' %}" method="post">
        {% csrf_token %}
        <input type="number" name="id" id="id" value="{{patient.id}}" hidden>

        <div class="container mt-4 mb-4">
            <textarea name="t1_1" class="form-control" id="t1_5" rows=""><p><strong>Remarks:</strong></p><p>&nbsp;</p><p>SITUS SOLITUS<br>LEVOCARDIA<br>ALL FOUR PULMONARY VEINS DRAINING INTO LA<br>IVC/SVC DRAINING INTO RA<br>NRGA<br>AV-VA CONCORDANCE<br>MORPHOLOGICALLY NORMAL VALVES<br>INTACT IAS and IVS<br>PULMONARY VALVE DOMING<br>SEVERE VALVULAR PS<br>RVOT GRADIENTS= PJV- cm/sec, PEAK- mmHg, MEAN- mmHg<br>OTHER VALVES MORPHOLOGICALLY NORMAL<br>NORMAL BIVENTRICULAR SYSTOLIC FUNCTION<br>NO PDA / COARCTATION OF AORTA<br>NO PERICARDIAL EFFUSION / VEGETATION</p><p>&nbsp;</p><p><strong>Impression:</strong></p><p>&nbsp;</p><p>ACYANOTIC CONGENITAL HEART DISEASE<br>SEVERE VALVULAR PS<br>&nbsp;</p></textarea>
        </div>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>